modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "mugann"
version = "${version}"
displayName = "Mugann: on the Study of Curses"
authors = ""
description = '''

'''
#logoFile = ""

[[dependencies.mugann]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mugann]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "mugann.mixins.json"
